### PR TITLE
Doug

### PR DESCRIPTION
**Pull request by nerdoug**
undated board diagrams

### CODE REVIEW

**Comment by va3wam** [comment]
I do not seem to be able to do anything with this (resolve conflict is greyed out for me). I am guessing that is because I was not specified as a contributor.  That said, I think that you are safe to simply resolve the conflict and approve this yourself. That should merge your Doug branch into master then you can delete the Doug branch on GitHub and then delete the Doug branch locally (along with the remote tracking using the -r parameter). I am pretty sure this is written up in the version control section of the wiki. Happy to help out if needed.

**Comment by nerdoug** [comment]
you're correct that I didn't put you as a reviewer on the pull, because I
didn't think there would be any conflicts.
I stand corrected on that one, and half of the files disappeared from the
doc directory on my PC. They're in the github doug branch, so I'm not
worried, just confused.  I'm working thru it slowly (partly because I
expect to be called to supper in minutes.)
Will let you know if I'm stuck.

<delliott@nds.com>Cheers,
    Doug Elliott  VA3DAE
    cell & text: 519-630-8925
    email: canoe.eh@gmail.com
    web:  http://nerdpit.ca
    "VA3DAE monitoring on VE3OME"

**Comment by nerdoug** [comment]
I renamed the offending file in my local directory, but wasn't allowed to commit / push it to master

**Comment by nerdoug** [comment]
backed up  the partial doc folder I have left, I fetched Doug branch, which got back all my files. I then deleted both pinout-CPU files hoping to enable merge. was able to commit and push. The merge message above now says there are no conflicts, and I can do an automatic merge, which I'll now do.

**Comment by nerdoug** [comment]
Seem to have pulled off the merge, but lost the latest version of the CPU pinouts in the process. Hoping that one of the versions in my downloads directory is current.

**Comment by va3wam** [comment]
Oh dear, that sucks. Hope you did not lose too much work. So sorry that this happened Doug

Andrew

**Pull request merged**
