### PR TITLE
Andrew

### PR DESCRIPTION
**Pull request by va3wam**
Complete replacement or original TWIPi code with telemetryDemo code. This code does not do PID logic or drive motors. It features DMP firmware for the MPU6050 and MQTT QOS1 messaging. There is a stability issue with the the MQTT code that needs to be sorted out. Also, this code uses an OLED not an LCD for output.

### CODE REVIEW

**Review by va3wam — COMMENTED** [review]
I am not sure what happened here

**Review by nerdoug — APPROVED** [review]

**Comment by nerdoug** [comment]
beautiful code

**Comment by va3wam** [comment]
That did not work. Lets try again!

**Comment by nerdoug** [comment]
think we're done

**Pull request merged**
