### PR TITLE
version 3 of pinouts-cpu

### PR DESCRIPTION
**Pull request by nerdoug**
2 non-text files, which git can't analyse line by line. One of them has a previous version already on Github, SB7d-pinouts-CPU.ods. I'm expecting git to say the merge can't be done because it's not willing to replace the old file with the same name without human supervision. The other file in the update, S7B-pinouts-CPU.pdf doesn't already exist in Github, so I expect it to be merge-able.

If things go as described, I'll have to find a way to delete the old version of the ods file from the Github master. Couldn't do that on the last orbit through this process, but I'm older and wiser now.

### CODE REVIEW

**Comment by nerdoug** [comment]
OK, I'm confused, but happy. need to check if right files ended up in origin/master.

**Comment by nerdoug** [comment]
yup, the right files are in master. Not sure what happened last time, but the simpler process has prevailed.

**Comment by nerdoug** [comment]
clicked the delete branch button in the webpage for the pull request, which is probably the origin version, but not my local version, so I'll go delete that now, with git branch -d -r origin/doug-pinouts

**Comment by nerdoug** [comment]
couldn't get that command to work: git branch -d -r origin/doug-pinouts
instead, I used: git branch -d doug-pinouts

**Comment by va3wam** [comment]
You have been busy!  Sounds like my instructions need work. I will see if I can improve them. In the mean time I think I can help clarify what is happening. I believe that The command 
> git branch -d -r origin/doug-pinouts
> 
Is interpreted as follows:

1. Origin is an alias for your remote repository. You can see your alias list by typing GIT remote -v or Git status -sb
2. The -d -r says delete the tracking branch
3. So this command says please delete the branch Doug-pinouts on the remote repository (github) And then remove the local tracking reference to that remote repository. I also think that you must first move out of that local branch by typing git checkout master.

Using Git status -sb after each command sort helps visualize what is going on. The repository that you are in has a * beside it. All local branches are one colour (green I think) and the remote branches are in a second colour (red I think).

 In this case i think that you are saying that you deleted the remote branch using your browser, which is what I did as well, so may get an error (not sure about that) but you will also remove the remote branch reference from your local Git repo. If you use Git status -sb before and after you will see the reference to the remote repository disappear.

 Also I think that your remote branch as called Doug not Doug-pinouts but I may be wrong about that.

Does that make sense? Perhaps I need to better document this? Perhaps I do not know what is going on? Likely all three are true 😀

Andrew

**Comment by va3wam** [comment]
Yes that is how I think it works. Of course my instructs may be wrong as you seem to have figured out. I will test and fix that procedure so we have a better reference next time we need it.

Andrew

**Comment by va3wam** [comment]
Yay! Look at us learning to use version control!

Andrew

**Pull request merged**
